from model.Pop import Pop
from model.MF import MF
from model.MultiMF import MultiMF
from model.PJFNN import PJFNN
from model.BPJFNN import BPJFNN
from model.APJFNN import APJFNN
from model.BERT import BERT
from model.VPJFv9 import VPJFv9
from model.LightGCN import LightGCN
from model.MultiGCN import MultiGCN
from model.MultiPJF import MultiPJF
from model.NCF import NCF